# Generated by Django 5.0.4 on 2024-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passalpages', '0002_rename_carts_info_itemsincart_cart_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='city',
            field=models.CharField(default='pp', max_length=50),
            preserve_default=False,
        ),
    ]
